spCreateState 'Andaman and Nicobar Islands'
spCreateState 'Andhra Pradesh'
spCreateState 'Arunachal Pradesh'
spCreateState 'Assam'
spCreateState 'Bihar'
spCreateState 'Chandigarh'
spCreateState 'Chhattisgarh'
spCreateState 'Dadra and Nagar Haveli and Daman and Diu'
spCreateState 'Delhi'
spCreateState 'Goa'
spCreateState 'Gujarat'
spCreateState 'Haryana'
spCreateState 'Himachal Pradesh'
spCreateState 'Jammu and Kashmir'
spCreateState 'Jharkhand'
spCreateState 'Karnataka'
spCreateState 'Kerala'
spCreateState 'Ladakh'
spCreateState 'Lakshadweep'
spCreateState 'Madhya Pradesh'
spCreateState 'Maharashtra'
spCreateState 'Manipur'
spCreateState 'Meghalaya'
spCreateState 'Mizoram'
spCreateState 'Nagaland'
spCreateState 'Odisha'
spCreateState 'Puducherry'
spCreateState 'Punjab'
spCreateState 'Rajasthan'
spCreateState 'Sikkim'
spCreateState 'Tamil Nadu'
spCreateState 'Telangana'
spCreateState 'Tripura'
spCreateState 'Uttar Pradesh'
spCreateState 'Uttarakhand'
spCreateState 'West Bengal'